# Generated by Django 4.1.3 on 2022-11-23 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Board',
        ),
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
        migrations.RenameModel(
            old_name='Gauges',
            new_name='Gauge',
        ),
        migrations.RenameModel(
            old_name='Measures',
            new_name='Measure',
        ),
        migrations.RenameModel(
            old_name='Boards',
            new_name='Sensor',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='magnitud',
            new_name='specs',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='specs',
            new_name='magnitud',
        ),
    ]
