# Generated by Django 4.1.3 on 2022-11-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sensors_board_rename_devices_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='specs',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='device',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor'),
        ),
    ]
