# Generated by Django 4.1.3 on 2022-11-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.board'),
        ),
        migrations.AlterField(
            model_name='device',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='api.device'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='api.sensor'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gauge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='api.gauge'),
        ),
    ]
