version: '3.9'

services:
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8020:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  mqtt_brocker:
    build: ./mosquitto/
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/mosquitto.conf
    ports:
    - 1884:1883
    depends_on:
      - db

  redis:
    image: redis:latest
    # restart: always
    volumes:
      - ./redis/data/:/data  
      - cache:/data 
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=super
      - POSTGRES_PASSWORD=super
      - POSTGRES_DB=science

volumes:
  postgres_data:
  cache: